# Generated by Django 5.0 on 2023-12-22 09:31

import dice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[dice.models.validate_name])),
                ('dice', models.IntegerField()),
                ('sides', models.IntegerField()),
                ('throws', models.CharField(max_length=255, validators=[dice.models.validate_throws])),
                ('sum', models.IntegerField()),
                ('modifier', models.CharField(blank=True, default='', max_length=255, validators=[dice.models.validate_modifier])),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
