# Generated by Django 5.0 on 2023-12-11 01:04

import dice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dice',
            name='modifier',
            field=models.CharField(blank=True, default='', max_length=255, validators=[dice.models.validate_modifier]),
        ),
        migrations.AlterField(
            model_name='dice',
            name='name',
            field=models.CharField(max_length=255, validators=[dice.models.validate_name]),
        ),
        migrations.AlterField(
            model_name='dice',
            name='throws',
            field=models.CharField(max_length=255, validators=[dice.models.validate_throws]),
        ),
    ]
