# Generated by Django 5.0 on 2023-12-11 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
