# Generated by Django 5.0 on 2023-12-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='rtmp_url',
            field=models.CharField(max_length=255),
        ),
    ]
