name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Test - (Dice) insert_dice_roll
      run: |
        python ./web/manage.py test dice.tests.DiceTestCase.test_insert_dice_roll_api

    - name: Run Test - (Dice) get_dice_rolls
      run: |
        python ./web/manage.py test dice.tests.DiceTestCase.test_get_dice_rolls_api
